### ISSUE TITLE
invalid_argument: Invalid argument: model does not implement `saveToken()`

### ISSUE THREAD

**Issue by kasunnirmala** [compwright/oauth2-server-mongoose#22]
I followed the guideline. But this following error occurs;

invalid_argument: Invalid argument: model does not implement `saveToken()`
    at new InvalidArgumentError (C:\LeMithuro\backend\node_modules\@compwright\oauth2-server\lib\errors\invalid-argument-error.js:21:14)        
    at new PasswordGrantType (C:\LeMithuro\backend\node_modules\@compwright\oauth2-server\lib\grant-types\password-grant-type.js:32:11)
    at TokenHandler.handleGrantType (C:\LeMithuro\backend\node_modules\@compwright\oauth2-server\lib\handlers\token-handler.js:230:10)
    at TokenHandler.<anonymous> (C:\LeMithuro\backend\node_modules\@compwright\oauth2-server\lib\handlers\token-handler.js:93:19)
    at TokenHandler.tryCatcher (C:\LeMithuro\backend\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\LeMithuro\backend\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (C:\LeMithuro\backend\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (C:\LeMithuro\backend\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\LeMithuro\backend\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (C:\LeMithuro\backend\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\LeMithuro\backend\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\LeMithuro\backend\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\LeMithuro\backend\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21) {
  statusCode: 500,
  status: 500,
  code: 500
}

**Comment by compwright** [comment]
@kasunnirmala Are you able to share a complete code sample that reproduces the issue?
